service: slack-app

provider:
  name: aws
  runtime: nodejs14.x

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any
